### ISSUE TITLE
"pip install geometric" installs an outdated version, incompatible with recent pyscf

### ISSUE THREAD

**Issue by alexmir18** [leeping/geomeTRIC#111]
Hi,
I discovered that "pip install geometric" and "conda install -c conda-forge geometric" produce different geometTRIC versions (0.9.7.1 and 0.9.7.2, respectively). The 0.9.7.1 version is incompatible with pySCF 1.7. No issues with 0.9.7.2.

**Comment by leeping** [comment]
Thank you for the issue report. I must have forgotten to update the version on pip, it is now updated. Please confirm and I will close the issue.
