### ISSUE TITLE
ORCA support request

### ISSUE THREAD

**Issue by chrinide** [leeping/geomeTRIC#122]
Dear developers,

Is there any play to the famous ORCA? A very powerful QC package.

**Comment by leeping** [comment]
Hello there,

I'm happy for ORCA to be included but I am not very familiar with the input file format.  Mainly someone who is familiar with the format needs to implement an Engine object and contribute it back to the main repository.

geomeTRIC does have an interface to QCEngine and that seems to have some ongoing Orca support: https://github.com/MolSSI/QCEngine/pull/178

Thanks,

- Lee-Ping

**Comment by stenczelt** [comment]
@leeping ASE has an ORCA calculator, with #129 you will have energies and forces with that immediately. ASE most likely cannot read hessians if ORCA can calculate and dump those.

**Comment by stenczelt** [comment]
see #143 now

**Comment by leeping** [comment]
Thanks a lot - I'm closing this because we should have ORCA support now through ASE.  Please submit a new issue if you encounter any trouble with using it.
