### ISSUE TITLE
New minor release?

### ISSUE THREAD

**Issue by robertodr** [leeping/geomeTRIC#128]
Hello, are you planning on cutting a new minor release? The current one is almost 2 years old.

**Comment by leeping** [comment]
Hello Roberto,

A new major release is planned with a great number of new features, including transition state optimization.  There are just too many features for me to release them one by one, and the large release takes time (also working on a publication describing some of the features).  Please stay tuned!

- Lee-Ping

**Comment by robertodr** [comment]
I understand, thanks for the reply! I'll stay tuned for 1.0

**Comment by robertodr** [comment]
Hello! I am re-opening this issue as I've found myself needing the latest `master` version in the shape of a conda package. I've ended up copy-pasting the `conda-forge` recipe and running my own build for a separate channel: https://anaconda.org/veloxchem/geometric Even an official pre-release would be very helpful for those, like me, relying on a conda package.

**Comment by leeping** [comment]
Thanks for the notification!  It's a high priority for me to "officially" release version 1.0 this summer.

- Lee-Ping

**Comment by robertodr** [comment]
Congratulations on the 1.0 release! This issue is no longer relevant and I'll close it.
