### ISSUE TITLE
Publish on PyPI?

### ISSUE THREAD

**Issue by avirshup** [leeping/geomeTRIC#13]
Lee Ping (et al.) - this is awesome! Are you considering publishing this on PyPI? It would be great to be able to include this as a normal dependency.

**Comment by dgasmith** [comment]
Hopefully not speaking for Leeping, but we will need them on PyPi/conda for a new database project that we are working on. We will get them up on the web sooner rather than layer.

**Comment by leeping** [comment]
Hello Aaron and Daniel,

I'm definitely interested in packaging and making this easy to install on both PyPI and conda. :)

**Comment by avirshup** [comment]
Great! It looks like the packaging is already pretty well taken care of, but please ping me if can help with anything along these lines

**Comment by leeping** [comment]
We've been working on fitting everything into a cookiecutter template (@yudongqiu did all of this). I don't know what's involved in listing a package on PyPI. I could figure this out myself but any time-saving pointers would be very helpful.

**Comment by avirshup** [comment]
So, here's my current practices:

1) Install [versioneer](https://github.com/warner/python-versioneer) into your project. After that, all you need to do to create a "release" is just `git tag` the relevant commit with your chosen version number.
2) Register for an account at [pypi](https://pypi.python.org/pypi)
3) [Set up travis to deploy to pypi when you tag a commit](https://docs.travis-ci.com/user/deployment/pypi/)

Conda and I still aren't friends, I'd defer to @dgasmith on that.

**Comment by leeping** [comment]
Thanks a lot. @yudongqiu : Have we installed versioneer into our project, or do we plan to?

**Comment by avirshup** [comment]
And actually, I can just send you PRs for steps 1 and 3 if you like

**Comment by dgasmith** [comment]
BTW @avirshup checkout the cookie cutter [here](https://github.com/choderalab/cookiecutter-compchem). That has conda-build tech natively there, its reasonably straightforward for pure Python projects.

**Comment by leeping** [comment]
Thanks, I've created the PyPy account (username is leeping). :)

**Comment by leeping** [comment]
Shall we make the current version "release 1.0"?

**Comment by avirshup** [comment]
OK, created a PR - #14 - for versioneer (that's the easy part).

**Comment by leeping** [comment]
Sorry, I got confused regarding the cookiecutter - we did that for a different but related project! It is also planned for this project.

**Comment by yudongqiu** [comment]
@leeping Yes, versioneer is included in the cookiecutter template which is adopted by the our crank project. https://github.com/lpwgroup/crank

**Comment by leeping** [comment]
I've tagged the current release as 0.8.

**Comment by leeping** [comment]
Any thoughts on why it's better to set up Travis to deploy, rather than using the command `python setup.py register sdist upload`?

**Comment by leeping** [comment]
Deploying Travis on PyPI requires adding my encrypted PyPI password to `.travis.yml` which in turn requires the Travis CLI, which is a Ruby gem. Attempting to install the gem failed on my system.

**Comment by leeping** [comment]
Thanks a lot, the tests are running now. I hope the password encryption worked.

**Comment by leeping** [comment]
The password encryption did work, but the deployment command was not running in the right folder.. trying again

**Comment by leeping** [comment]
Okay, here's the current error message.  I'm about to head into a meeting and will revisit later today.

```Uploading distributions to https://upload.pypi.org/legacy/
Uploading geometric-0.8+2.g1f636f3.tar.gz

  0% 0.00/124k [00:00<?, ?B/s]
100% 124k/124k [00:00<00:00, 452kB/s]
HTTPError: 400 Client Error: '0.8+2.g1f636f3' is an invalid value for Version. Error: Cannot use PEP 440 local versions. see https://packaging.python.org/specifications/core-metadata for url: https://upload.pypi.org/legacy/

travis_fold:end:dpl.3
__pycache__/versioneer.cpython-36.pyc already exists, no checkout
geometric.egg-info/PKG-INFO already exists, no checkout
geometric.egg-info/SOURCES.txt already exists, no checkout
geometric.egg-info/dependency_links.txt already exists, no checkout
geometric.egg-info/entry_points.txt already exists, no checkout
geometric.egg-info/requires.txt already exists, no checkout
geometric.egg-info/top_level.txt already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy```

**Comment by leeping** [comment]
I think the main error message is `Error: Cannot use PEP 440 local versions`

**Comment by avirshup** [comment]
Oh, I think this is because you've moved on past the commit you've originally tagged. To fix this, you can either
1. Delete your original "0.8" tag and re-apply it to the latest commit, or
2. Just tag the latest commit with "0.8.1" (or 0.8.1b1 or 08.1rc1 - [pep440](https://www.python.org/dev/peps/pep-0440/) provides some guidance on this)

**Comment by leeping** [comment]
The error message is now:

`Skipping a deployment with the pypi provider because this branch is not permitted`

**Comment by leeping** [comment]
Any idea why this error is appearing? I thought we were on the master branch.

**Comment by leeping** [comment]
All right, the error is now: `The user 'leeping' is not allowed to upload to project 'geometric'.`. I think that's because the module name on PyPI is taken. Could we change the package name on PyPI without changing the name of the GitHub repository?

**Comment by leeping** [comment]
We wrote a nice letter to the owner of the geometric package on PyPI and he has agreed to transfer the package ownership to us.  Version 0.8.6 is now live!

**Comment by leeping** [comment]
The remaining question is whether we should automate releases from Travis or do them manually.  I have heard arguments in favor of both options.
