### ISSUE TITLE
Using all the cores while minimizing the structure

### ISSUE THREAD

**Issue by 1heman** [leeping/geomeTRIC#137]
Hi,

I am using geomeTRIC in the following way
`geometric-optimize --psi4 input.in`

How do I ensure that I am using all the cores of my system? Are there any ways to reduce the duration it takes to optimize the structures?

Regards,
Hemant

**Comment by leeping** [comment]
Sorry for the late reply - for Psi4, you only need to specify `--nt 4` to ask Psi4 to use 4 threads (for example).  GeomeTRIC itself only uses a negligible amount of CPU resources compared to the electronic structure method.
