### ISSUE TITLE
Add option to allow success on reaching maxiter

### ISSUE THREAD

**Issue by jchodera** [leeping/geomeTRIC#156]
For some QCFractal OptimizationDataset workflows, it would be very useful to take at most K optimization steps and still return successful completion. For example, when starting from snapshots sampled from an MM surrogate potential at 300K, the initial QM energies may be too high, but a few steps of optimization is sufficient to explore the thermodynamically relevant energy surface in the vicinity of the starting geometry.

QCFractal / QCEngine appears to call geomeTRIC in a manner that passes in a JSON document via [run_json](https://github.com/leeping/geomeTRIC/blob/9981b39fa83b6e4cc0e369a05d615235cc639458/geometric/run_json.py#L190). Options such as whether to use `tric` or `cart` appear to be passed this way. If an option such as `success_on_maxiter` could be passed to signal that reaching `maxiter` should still successfully return completion of the optimization trajectory, this use case could easily be supported.

**Comment by leeping** [comment]
This has been implemented and merged into master now.  It should be part of release v1.1.  Thanks for your patience. :)

**Comment by jchodera** [comment]
Thank you!
