### ISSUE TITLE
[PYSCF] Geometry Optimisation - No message of failing to converge within the maxsteps

### ISSUE THREAD

**Issue by calvinp0** [leeping/geomeTRIC#191]
Hi, I posted this question to the PySCF group and I was directed to here in hopes of solving this issue

Link: https://github.com/pyscf/pyscf/issues/2031

As you see, when I run PySCF and use geomeTRIC for the optimisation with 100 maxstreps, the output from geomeTRIC does not inform me of failing to converge. I am uncertain why this is the case.

Now, I am not certain if this is related to PySCF but when I do `mol_opt.converged` in my code, I get the return `False`. Which I would say is my solution, but I have also noticed that if I do have a molecule that does converge, `mol_opt.converged` will still return `False`

Thanks for any help!

**Comment by leeping** [comment]
Hello Calvin,

I can see that your original issue regarding querying convergence success / failure has been resolved on the PySCF forum.  However, I'm concerned that you are seeing a convergence failure with 100 steps for such a small molecule.  I viewed your structure, which seems to be an organic radical, and I think it should have converged in 20 steps or less.  I tried to reproduce the job in Q-Chem and indeed it converged in 17 steps.

Geometry optimization can sometimes fail if the nuclear gradient of the energy is not accurate.  This is one possible cause of the issue, but it could be something else altogether.  

- Lee-Ping

[org-rad.zip](https://github.com/leeping/geomeTRIC/files/14041415/org-rad.zip)

**Comment by ganfisher** [comment]
> Hello Calvin,
> 
> I can see that your original issue regarding querying convergence success / failure has been resolved on the PySCF forum. However, I'm concerned that you are seeing a convergence failure with 100 steps for such a small molecule. I viewed your structure, which seems to be an organic radical, and I think it should have converged in 20 steps or less. I tried to reproduce the job in Q-Chem and indeed it converged in 17 steps.
> 
> Geometry optimization can sometimes fail if the nuclear gradient of the energy is not accurate. This is one possible cause of the issue, but it could be something else altogether.
> 
> * Lee-Ping
> 
> [org-rad.zip](https://github.com/leeping/geomeTRIC/files/14041415/org-rad.zip)

So, how can I handle with the unconverged nuclear gradients?
