### ISSUE TITLE
NumPy Matrix Deprecation

### ISSUE THREAD

**Issue by dgasmith** [leeping/geomeTRIC#34]
As a note, NumPy is deprecating the Matrix class. Users of `geometric` will increasingly see code blocks with the following warnings:

```
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/geometric/rotate.py:65: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  ymat = np.matrix(y).T
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py:68: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  return matrix(data, dtype=dtype, copy=False)
```

**Comment by leeping** [comment]
Thanks for the notification.  This seems troublesome ... is there an easy way to patch the code while making sure all the linear algebra is still right?

**Comment by dgasmith** [comment]
Unfortunately not really. Changes like this are normally validated via a full test suite. You can also attempt to compare operational pathways directly by leaving the matrix operations in place, adding an array routine, and using a `assert np.allclose` for each call until you are satisfied the code is producing the same results.

**Comment by leeping** [comment]
Thanks. I only used matrices when matrix multiplications were actually needed, and converted them back shortly afterward.  Otherwise it became too confusing to remember whether a variable somewhere was an array or a matrix.  It should be straightforward to make the changes.

**Comment by dgasmith** [comment]
You may be interested in the Python 3.5 `@` [operator](https://www.python.org/dev/peps/pep-0465/).

**Comment by leeping** [comment]
Thanks for letting me know about this - it seems very nice, though I might prefer to use `numpy.dot` for now for Python 2.7 compatibility reasons.

**Comment by leeping** [comment]
Marking this as resolved, thanks again for the heads-up.
