### ISSUE TITLE
Example of partial constraints input

### ISSUE THREAD

**Issue by bgobbi** [leeping/geomeTRIC#55]
I would like to run a minimization with al heavy atoms fixed (only H atoms optimized).
Is there an example of how to do this with geometric?
Thanks,
Alberto

**Comment by bgobbi** [comment]
I have found this posting maybe I understand it now. is this the correct input?
```$freeze
xyz 1 2 4 7 8
```
provided the atoms 1,2,4,7 and 8 are the non-hydrogen atoms?
Do the numbers start with 0 or 1?
Thanks,
Alberto

**Comment by leeping** [comment]
The numbers start with 1 in the constraints.txt file.

Thanks,

- Lee-Ping

**Comment by bgobbi** [comment]
I tired calling ```ParseConstraints()``` with this constraint string:
```
$freeze
xyz 1 5 6 9 10 12 13 14 16 17 18 19 22 25 26 29 32 34 35 36 37 39 40 41 42 43 45 47 49 52
```
but I got this error:
```
  File "C:\Users\albertgo\Documents\dev\geomeTRIC\geometric\optimize.py", line 356, in ParseConstraints
    raise RuntimeError("For this line:%s\nExpected %i tokens but got %i" % (line, ntok+1, len(s)))
RuntimeError: For this line:xyz 1 5 6 9 10 12 13 14 16 17 18 19 22 25 26 29 32 34 35 36 37 39 40 41 42 43 45 47 49 52
Expected 2 tokens but got 31
```
Can you tell me what I am doing wrong?
Thanks!

**Comment by bgobbi** [comment]
I figured it out.
here is the correct string:
```
$freeze
xyz 1,5,6,9,10,12,13,14,16,17,18,19,22,25,26,29,32,34,35,36,37,39,40,41,42,43,45,47,49,52
```
