### ISSUE TITLE
Improve QM gradient output error handling

### ISSUE THREAD

**Issue by yudongqiu** [leeping/geomeTRIC#67]
As discussed 3/12/2019 with @leeping, it is useful to implement a consistent error code, for failures of QM gradient jobs. 

The current error behavior is engine-dependent, which means when QM failure happens, some engine like Psi4 will trigger a RuntimeError, some may trigger other error types.

The improved error handling should return a consistent error code when such failure happens. Something like:
```
Exit with code 99.
QMError: "Gradient job failed"
```

Another custom type of error could be something like:
```
Exit with code 98.
NotConvergedError: "geomeTRIC optimization failed to converge in 50 iterations"
```

With the improved error handling, programs that call `geomeTRIC` by CLI, such as `torsiondrive`, will be able to get information about errors happened in `geomeTRIC` and determine what to do next.

**Comment by leeping** [comment]
Is this issue resolved with the current implementation of error codes?  I am not sure because you mentioned it would be nice to have a unified error code in this issue, but we ended up implementing a different error class for each engine.

**Comment by yudongqiu** [comment]
Yes the unified error code is `51` for the EngineError

**Comment by leeping** [comment]
Thanks, I'm closing the issue then.
