### ISSUE TITLE
AttributeError: 'CartesianCoordinates' object has no attribute 'Prims'

### ISSUE THREAD

**Issue by sunqm** [leeping/geomeTRIC#69]
This is the issue found in https://github.com/sunqm/pyscf/issues/6

This error may not be easy to reproduce because geometric/internal.py" L3021 was not triggered in new runs

**Comment by leeping** [comment]
I think I fixed the error but I couldn't reproduce what led up to it (https://github.com/leeping/geomeTRIC/pull/70).  That code is only called in case of critical failures of the coordinate system (fails to rebuild twice in a row and then goes to Cartesian coordinates).  Continuing the discussion here: https://github.com/sunqm/pyscf/issues/6

**Comment by sunqm** [comment]
Great, thanks!
