### ISSUE TITLE
geomeTRIC no longer producing .xyz file

### ISSUE THREAD

**Issue by CRingrose94** [leeping/geomeTRIC#75]
Using geomeTRIC to optimise a molecule used to produce an opt.xyz file however now only a state_optim.xyz is produced. Is there a command-line argument which can be used to produce the opt.xyz again? Not sure if this is a bug or a deliberate change. Thanks.

**Comment by leeping** [comment]
Hello Chris,

Thanks for your question, this is a deliberate change.  There is no command line option to bring back opt.xyz again, but we could consider adding it back.  The contents of opt.xyz are identical to the last frame in state_optim.xyz.

Thanks,

- Lee-Ping

**Comment by leeping** [comment]
Just following up; can you let me know if using `state_optim.xyz` will suit your needs, or is there a need for creating a separate `opt.xyz` file?

**Comment by CRingrose94** [comment]
Hi Lee Ping, thanks for the reply. 

We've implemented a fix which just extracts the opt.xyz from the state_optim.xyz so it's not needed for us anymore.

We may be moving to use QCEngine as a wrapper for GeomeTRIC soon too, so reading the xyz files may be avoided entirely.

Thanks,
Chris Ringrose
