### ISSUE TITLE
Use Psi4's JSON input/output compute module

### ISSUE THREAD

**Issue by dgasmith** [leeping/geomeTRIC#8]
It would be a good idea for geomeTRIC to output/consume Psi4's current JSON specification found [here](https://github.com/psi4/psi4/blob/master/psi4/driver/json_wrapper.py#L52). This will make it quite a bit easier to build input jobs and avoid parsing the Psi4 log files. A gradient example can be found [here]
(https://github.com/psi4/psi4/blob/master/tests/json/gradient/input.py).

The ultimate goal is to interface the code with the expanding [MolSSI QC Schema](
https://github.com/MolSSI/QC_JSON_Schema) so that it can operate with any code that follows the schema. However this schema isn't quite at the point where it can be adopted.

**Comment by loriab** [comment]
BTW, I have geomeTRIC communicating with Psi4 via json in a _very_ dev version. I'll consult with you later, just wanted to post here so I'm in the loop on this issue.

**Comment by leeping** [comment]
Hi Lori,

Thanks for letting me know. :)  I look forward to seeing how this works.

- Lee-Ping

**Comment by loriab** [comment]
@leeping, just to be sure, `coords` are expected to be in Angstroms [here](https://github.com/leeping/geomeTRIC/blob/master/geometric/engine.py#L372) for storage in `self.M` in Ang, while `coords` [here](https://github.com/leeping/geomeTRIC/blob/master/geometric/engine.py#L378) are in Bohr then converted to Ang for storage in `self.M` and rewriting the psi input template? That seemed to fit the unit conversion pattern, but I didn't see anything explicit in forcebalance molecule, so thought I'd check.

**Comment by leeping** [comment]
You're right. Generally, the `Molecule` object always expects the Cartesian coordinates to be in Angstrom, whereas the Optimize() function [here](https://github.com/leeping/geomeTRIC/blob/master/geometric/optimize.py#L854) expects the Cartesian coordinates to be in Bohr.

**Comment by dgasmith** [comment]
Effectively fixed in #16.
