### ISSUE TITLE
Bug for constraints type "xyz" in run_json.py

### ISSUE THREAD

**Issue by yudongqiu** [leeping/geomeTRIC#85]
### Explanation:
Four constraint types are supported, namely `["xyz", "distance", "angle", "dihedral"]`, the current implementation is correct for the last three, such as `distance 1 2` or `angle 1 2 3`, but is **incorrect** for the "xyz", because to freeze the xyz of atoms 0-2, it will generate string `"xyz 1 2 3"`, which will trigger an error by geomeTRIC. The correct string should be `"xyz 1-3"` or `"xyz 1,2,3"`

### Solution:
For the special case of constraint type "xyz", it would be useful to call the `nifty.commadash()` function  instead of adding indices:
old:
```
const_rep.extend([x + 1 for x in constraint["indices"]])
```

new:
```
from geometric.nifty import commadash
...

if constraint["type"] == "xyz":
    const_rep.append(commadash(constraint["indices"]))
else:
    const_rep.extend([x + 1 for x in constraint["indices"]])
```

**Comment by leeping** [comment]
Could you submit a PR with this change?  :)  Does this affect anything outside of geomeTRIC (i.e. things on the QCFractal side)?

**Comment by yudongqiu** [comment]
Sure. I think if QCFractal tries to call `geometric.run_json.geometric_run_json()` with the "xyz" constraints, it will result in an error in the current implementation. Fixing the bug here should fix it for QCFractal, too.

**Comment by dgasmith** [comment]
+1 for @yudongqiu's comment. Since we pass through options this will work just fine.
