### ISSUE TITLE
Use of `os.exit` makes geomeTRIC unusable in pipelines

### ISSUE THREAD

**Issue by dgasmith** [leeping/geomeTRIC#90]
Currently if there is an issue with an execution the use of `os.exit` is used which will exit out of all python layers, see [here](https://github.com/leeping/geomeTRIC/blob/master/geometric/optimize.py#L1335). This currently crashes entire QCArchive pipelines making use of geomeTRIC. The use of `os.exit` outside of command line tools is a very bad idea for exactly this reason.

An implementation that would give you the same functionality [here](https://github.com/leeping/geomeTRIC/blob/master/geometric/optimize.py#L1884):

```
try:
    run_optimizer(**vars(args))
except MyError:
    os.exit(51)
...
```

**Comment by leeping** [comment]
@yudongqiu Could you please make the necessary change and create a PR?  I'll cut a release as soon as possible.

**Comment by yudongqiu** [comment]
@dgasmith @leeping Sure I will fix this asap.
