### ISSUE TITLE
OpenMM warning log

### ISSUE THREAD

**Issue by dgasmith** [leeping/geomeTRIC#92]
Currently if OpenMM cannot be found a `logger.info` is thrown which may confuse some users as it does not harm canonical operations. Can we either change this to `logger.warning`, eliminate the warning, or similar instead which would be more consistent with other engines (e.g., cannot find Molpro). Line is [here](https://github.com/leeping/geomeTRIC/blob/1d8a390a6e24bd0bcdb32e5e90a3efce20c249e0/geometric/molecule.py#L333).

**Comment by leeping** [comment]
I think changing to `logger.warning` would be the easiest. Would that enable us to filter it out?

**Comment by dgasmith** [comment]
Apologies, I was going the wrong way :). A `logger.debug` is the way to go so this would not show up in normal info printing. But yes, that would be easy and would fix lots of potential confusion.

**Comment by leeping** [comment]
I made the changes in #93 and will make another release soon.

**Comment by dgasmith** [comment]
Thanks! No rush on the release as this just effects logging.

**Comment by leeping** [comment]
Is this issue resolved as well?

**Comment by dgasmith** [comment]
It is! Thank you.
