### ISSUE TITLE
Failed on creating a new Cartesian with the old Cartesian and the different in internal coordinate

### ISSUE THREAD

**Issue by chenruduan** [leeping/geomeTRIC#99]
Hi,

I am trying to use some functions in this TRIC package. Basically I would like to generate a new molecule in Cartesian coordinate given its old Cartesian coordinate and their difference in the internal coordinate. I would like to use TRIC because it gives a convenient representation (6 extra scalar numbers) of sub-molecules assuming their primitive ICs are known.

As a test, I started with a case of two water molecules (two_water.xyz). I made a translation  (two_water_trans.xyz) and a translation plus rotation (two_water_trans_rot.xyz) of the second water molecule and tried to use the newCartesian function to generate the new Cartesian. The procedure is the following,

mol = Molecule(fnm='mol.xyz', ftype='xyz');
mol2 = Molecule(fnm='mol2.xyz', ftype='xyz')
tric = DelocalizedInternalCoordinates(mol, build=True, connect=False, addcart=False, conmethod=1)
tric.Prims.newCartesian(mol.xyzs[0].flatten(), tric.Prims.calcDiff(mol2.xyzs[0], mol.xyzs[0])).reshape(-1, 3)

This works for translation (two_water.xyz as mol and two_water_trans.xyz as mol2) but not for translation plus rotation (two_water.xyz as mol and two_water_trans_rot.xyz as mol2). In the latter case, the generated Cartesian coordinates break the second water molecule. I attach the three xyz files and a jupyter notebook in the zip file that could reproduce the behavior.

Any help will be appreciated!

[two_water.zip](https://github.com/leeping/geomeTRIC/files/3704095/two_water.zip)

**Comment by leeping** [comment]
Hello Chenru,

Thank you for your message. I haven't tested your case yet, but I wanted to ask if the `mol.xyz` and `mol2.xyz` file contain geometries that are very different.

The `newCartesian()` function uses nonlinear iterations to find the new geometry, so I only expect that it will work for small differences in the geometry.  If you could explain the bigger picture of what you're trying to do, I may be able to help.

Thanks,

- Lee-Ping

**Comment by chenruduan** [comment]
Hi Lee-Ping,

For each sub molecule (water), the geometry stays the same in mol.xyz and mol2.xyz. However, your are right that the relative orientation are very different (compared to the geometry update in a regular geometry optimization). I would say the same for those two pairs of geometries (two_water, two_water_trans and two_water, two_water_trans_rot). 

I noticed in the SI of TRIC paper it is stated that the new Cartesian is obtained iteratively because of the non-linear nature of the transformation between Catesian coordinate and IC. The may indeed be a reason but I may first want to make sure I did not do something wrong in my code.

What I want to achieve here, is to find a simple description of the relative orientations of many sub molecules, where no symmetry is assumed. So that given the primitive IC (Z matrix), this description, and a reference, I could generate a new Cartesian coordinate for these sub molecules as a super molecule. What I reported initially is an attempt to used the old Cartesian coordinate as a reference and extra TRIC internal coordinates (3 translational and 3 rotational DOF) as the description.

Thanks for your speedy reply and please let me know if anything is unclear.

Chenru

**Comment by leeping** [comment]
Hello Chenru,

I took a look at your job and noted some small corrections.  After making the corrections, your job worked and there's nothing that seemed out of the ordinary.  

The main thing is that the `InternalCoordinates` API requires coordinates in atomic units, so when you supplied the input coordinates in Angstrom, it may have calculated the displacement incorrectly.

The below code generates the XYZ coordinates you need and also prints out the differences in internal coordinates.  The output XYZ coordinates matches closely with two_water_trans_rot.xyz.  Note that the matching is not "incredibly" close (i.e. the largest deviation is ~3e-3 a.u.); that could be because you supplied a test geometry where the rotation angle was exactly π.  This is a kind of worst-case scenario for the rotation codes, because there is a degeneracy in the exponential map representation of rotations for rotations of π radians.  If you supply any other rotation, I think the agreement would be a lot closer.

Script:

```
#!/usr/bin/env python

from geometric.nifty import ang2bohr
from geometric.molecule import Molecule
from geometric.internal import DelocalizedInternalCoordinates

mol = Molecule(fnm='two_water.xyz', ftype='xyz');
mol2 = Molecule(fnm='two_water_trans_rot.xyz', ftype='xyz')
tric = DelocalizedInternalCoordinates(mol, build=True, connect=False, addcart=False, conmethod=1)

diff = tric.Prims.calcDiff(mol2.xyzs[0], mol.xyzs[0])

# Print primitive names and 'actual' differences (i.e. divided by scale factor)
for p, d in zip(tric.Prims.Internals, diff):
    print(p, d/p.w if hasattr(p, 'w') else 1.0)

x1 = mol.xyzs[0].flatten() * ang2bohr
x2 = mol2.xyzs[0].flatten() * ang2bohr

x_new = tric.Prims.newCartesian(x1, tric.Prims.calcDiff(x2, x1))

print(x_new - x2)

mol.xyzs[0] = x_new.reshape(-1,3) / ang2bohr
mol.write('two_water_trans_rot_new.xyz')
```

Output:

```
Distance 1-3 1.0
Distance 1-5 1.0
Distance 2-4 1.0
Distance 2-6 1.0
Angle 3-1-5 1.0
Angle 4-2-6 1.0
Translation-X 1,3,5 [0. 0. 0.]
Translation-X 2,4,6 [0.92514 0.92514 0.92514]
Translation-Y 1,3,5 [0. 0. 0.]
Translation-Y 2,4,6 [1.41426 1.41426 1.41426]
Translation-Z 1,3,5 [0. 0. 0.]
Translation-Z 2,4,6 [-1.29107 -1.29107 -1.29107]
Rotation-A 1,3,5 0.0
Rotation-A 2,4,6 2.5035049509469794e-16
Rotation-B 1,3,5 0.0
Rotation-B 2,4,6 3.141592653589793
Rotation-C 1,3,5 0.0
Rotation-C 2,4,6 2.1367205053011828e-16
[-8.88178420e-16  0.00000000e+00 -2.22044605e-16 -2.28515154e-04
  4.00460903e-05  2.27084810e-03 -8.88178420e-16  0.00000000e+00
  0.00000000e+00  5.98426546e-04  1.71187930e-03  3.60972473e-04
 -1.33226763e-15  1.11022302e-16  0.00000000e+00 -3.69911393e-04
 -1.75192539e-03 -2.63182057e-03]
```

**Comment by chenruduan** [comment]
Hi Lee-Ping,

Thanks so much for you help. The problem is resolved on several other cases I tested by converting the xyz into bohr. I will close the issue.
